### ISSUE TITLE
test_twolayer_qq test fails

### ISSUE THREAD

**Issue by rabernat** [rabernat/pyqg#2]
Despite our best attempt at making a useful test, the default test still fails. Here is the output I get from it.

```
FAIL: test_twolayer_qg.test_the_model
Make sure the results are correct within relative tolerance rtol.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/rpa/pyqg/pyqg/tests/test_twolayer_qg.py", line 42, in test_the_model
    np.testing.assert_allclose(q1norm, 9.561430503712755e-08, rtol)
  File "/usr/local/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/local/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-15, atol=0

(mismatch 100.0%)
 x: array(9.723198783759038e-08)
 y: array(9.561430503712755e-08)
-------------------- >> begin captured stdout << ---------------------
t=               0, tc=         0: cfl=0.021228, ke=0.000019292, T_e=527.025961099
t=        12800000, tc=      1000: cfl=0.021195, ke=0.000019292, T_e=527.025961099
t=        25600000, tc=      2000: cfl=0.021309, ke=0.000035737, T_e=387.206968354
t=        38400000, tc=      3000: cfl=0.026747, ke=0.000089140, T_e=245.170789728
t=        51200000, tc=      4000: cfl=0.042333, ke=0.000222572, T_e=155.154023419
t=        64000000, tc=      5000: cfl=0.066459, ke=0.000555989, T_e=98.164418796
t=        76800000, tc=      6000: cfl=0.105021, ke=0.001390120, T_e=62.085201635
t=        89600000, tc=      7000: cfl=0.102573, ke=0.003476802, T_e=39.257825464
time:       9.3312e+07
q1norm:     9.723198783759038e-08

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 4 tests in 14.851s

FAILED (failures=1, errors=1)
```

**Comment by rabernat** [comment]
Here are the values that I needed to use to make the test pass

```
time:       9.3312e+07
q1norm:     9.723198783759038e-08
EKE1:       5.695448642915733e-03
EKE2:       1.088253274803528e-04
APEge:     8.842056320175081e-08
EKEdiss:    6.368668363708053e-08
entspec:    5.703438193477885e-07
apeflux:    9.192940039964286e-05
KEflux:     1.702621259427053e-04
APEgenspec: 9.058591846403974e-05
KE1spec:    3.338261440237941e+03
KE2spec:    7.043282793801889e+01
```

**Comment by MFJansen** [comment]
I'm confused, did you just change what the "right" answer should be, such as to make the test pass?
If I remember correctly these answer were based on previous versions of the model (including the original matlab code) and carried through with various modifications. If we are not getting these answers anymore we should figure out why, right?

**Comment by rabernat** [comment]
I don't remember exactly what happened. But the test has not worked for me for a long time.

**Comment by rabernat** [comment]
To complicate things further, I changed the test results again just now, again setting the values to whatever was need to make the test pass. It passed on one computer (linux workstation) but failed on another (macbook). So there is also a precision problem.

```
time:       9.3312e+07
   EKEdiss: 6.370944436469275e-08 
            6.368668363708053e-08 (desired)
    APEgen: 8.845995860946115e-08 
            8.842056320175081e-08 (desired)
      EKE2: 1.088678973447847e-04 
            1.088253274803528e-04 (desired)
      EKE1: 5.697425547471293e-03 
            5.695448642915733e-03 (desired)
   KE2spec: 7.045799964299876e+01 
            7.043282793801889e+01 (desired)
    KEflux: 1.701656541188276e-04 
            1.702621259427053e-04 (desired)
   APEflux: 9.192892981541655e-05 
            9.192940039964286e-05 (desired)
   KE1spec: 3.339146950169072e+03 
            3.338261440237941e+03 (desired)
APEgenspec: 9.062527901111530e-05 
            9.058591846403974e-05 (desired)
   entspec: 5.705171842744948e-07 
            5.703438193477885e-07 (desired)
```

This is a separate issue though from whether the results agree with your original code. My vague recollection was that there was some outstanding issue regarding the number of the timesteps.

Anyway, we should try to sort out what is going on. I preserved the old test values in the comments section.

**Comment by MFJansen** [comment]
I must admit that I haven't used python for a while - and in particular not since I got my new computer - so I just installed canopy... Anyway once I'm back up to speed I might try to go back and check where (and why) the test starts failing. Seems like that's the thing that should be done.

**Comment by rabernat** [comment]
I just confirmed that the original test does succeed on the mac pro, which was the machine we used to develop the code over the summer. So something changed since then. I just pushed a branch called test_twolayer_succeeds from that code.

**Comment by MFJansen** [comment]
I switched to the branch you created. The test still fails for me though less badly then with the new version of the code, so there are definitely differences. For the future, we should run the tests for every possibly significant change we make. If one fails, we need to figure out why, and wether we think that the new results are nevertheless "correct" - if so we need to change the test so that it passes again.

**Comment by MFJansen** [comment]
I just pulled the latest version on my old laptop. The version on the "test_twolayer_succeeds"  branch passes the test on my laptop. As I said earlier, on my desktop it failed, but less badly - so it might be a machine dependent numerics issue. However, that still seems a bit odd to me, given that it does work on my laptop and your desktop, which are just as different machines. Moreover I seem to recall that we were able to reproduce results to this precision even between the Matlab and python codes. Can somebody else checkout the "test_twolayer_succeeds" branch and check if it passes on their machine?

The master branch version now seems totally off, and also the test script itself seems to keep changing. Can we please restore the original test, so that we can make sure our answers haven't changed (and if they did, figure out why)?

**Comment by rabernat** [comment]
Here is what happened. Cesar asked if he could make changes to the code to make it more efficient. I ran the test on my laptop using the most recent code I had (basically unchanged since summer), and it failed. So I told him that the tests were broken, and that he should just make his changes without worrying about the tests. (Which completely defeats the point of the tests, I know.) So yes, now we have to go through and figure out when and how the tests broke.

**Comment by rabernat** [comment]
So I just tried test_twolayer_succeeds on my linux workstation and it failed!

```
time:       9.3312e+07
q1norm:     9.564110327663224e-08
Traceback (most recent call last):
  File "pyqg/tests/test_twolayer_qg.py", line 89, in <module>
    test_the_model()
  File "pyqg/tests/test_twolayer_qg.py", line 42, in test_the_model
    np.testing.assert_allclose(q1norm, 9.561430503712755e-08, rtol)
  File "/usr/local/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/local/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-15, atol=0

(mismatch 100.0%)
 x: array(9.564110327663224e-08)
 y: array(9.561430503712755e-08)
```

This is the result that caused me to initially doubt that the test worked at all. From this I can conclude that our test result, despite the reproducibility we found between matlab and python, still had some sort of platform dependence. I am wondering if this is an anaconda vs canopy issue. (The machine the test failed from was anaconda.)

**Comment by rabernat** [comment]
No, it is not a canopy vs. anaconda issue. I just tried test_twolayer_succeeds on my laptop (canopy 64-bit) and it failed too.

```
time:       9.3312e+07
q1norm:     9.565695883770874e-08
Traceback (most recent call last):
  File "pyqg/tests/test_twolayer_qg.py", line 89, in <module>
    test_the_model()
  File "pyqg/tests/test_twolayer_qg.py", line 42, in test_the_model
    np.testing.assert_allclose(q1norm, 9.561430503712755e-08, rtol)
  File "/Users/rpa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/testing/utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "/Users/rpa/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-15, atol=0

(mismatch 100.0%)
 x: array(9.565695883770874e-08)
 y: array(9.561430503712755e-08)
```

**Comment by crocha700** [comment]
It fails on my Mac Pro too (anaconda 64). But as Malte notes it fails less badly than the master branch.  So I think the problem with the master branch is that I changed with "fft2" with "rfft", which explores the Hermitian symmetry of the Fourier coefficients and returns only half of them. With "rfft" we store less and compute less, though we have the same information.

So it is possible that something is missing in the diagnostics (say a factor of 2, etc...). I did not work on that because I did not know where those number come from. Ryan, can you restore the previous number to the test of the master branch, so that can try to figure that out...


<pre><code>
time:       9.3312e+07
q1norm:     9.565695883770874e-08
Traceback (most recent call last):
  File "test_twolayer_qg.py", line 89, in <module>
    test_the_model()
  File "test_twolayer_qg.py", line 42, in test_the_model
    np.testing.assert_allclose(q1norm, 9.561430503712755e-08, rtol)
  File "/Users/crocha/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/Users/crocha/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-15, atol=0

(mismatch 100.0%)
 x: array(9.565695883770874e-08)
 y: array(9.561430503712755e-08)

</code></pre>

**Comment by crocha700** [comment]
Don't worry about changing it. I just realized that it is comment out in the code. Let's figure out what's going on, and then we change.

**Comment by rabernat** [comment]
So we really have two separate issues:

1. The lack of platform independence in the original (pre-Cesar) tests.
2. The additional stuff that broke when Cesar made his updates.

I could imagine how to make progress on 2: going through the diagnostics and trying to understand how they are different using the rfft representation. What the diagnostics do now is just take the average of the abs of certain spectral components. A more robust approach would be to actually use the parseval relations to take well-defined norms of the spectra. This should be done from within a working test_twolayer_succeeds branch. 

But I have no idea how to fix 1.

**Comment by MFJansen** [comment]
Is 2. only a diagnostics problem? There seem to be relatively large deviations in the "q1norm" test diagnostic, which is really just the squared sum of q1 at all gridpoints.

With regards to 1., interestingly some of the "failed" test cases seem to show identical results to each other - despite being run on different platforms (e.g. Ryan's Laptop and Cesar's Mac Pro). That might provide a starting point to try and trace what exactly causes the differences. The question is whether we care enough about bitwise reproducibility to go through the effort to really get to the bottom of this.

**Comment by crocha700** [comment]
Good point. So I've changed two other things besides the fft: implemented a AB3 scheme for time-stepping and changed the coefficient of the filter from 18.4 to 24.5. The former is used for single precision. The basic idea is to choose this coefficient is to require that the fourier coefs are zero to within machine precision for k > k_cutoff (see Joe LaCasce's thesis).

Reverting these two changes the q1norm test fails "less badly" on my MacPro (anaconda 64-bit)

<p><code>
q1norm:     9.560060475638711e-08
Traceback (most recent call last):
  File "test_twolayer_qg.py", line 89, in <module>
    test_the_model()
  File "test_twolayer_qg.py", line 42, in test_the_model
    np.testing.assert_allclose(q1norm, 9.561430503712755e-08, rtol)
  File "/Users/crocha/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/Users/crocha/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-15, atol=0

(mismatch 100.0%)
 x: array(9.560060475638711e-08)
 y: array(9.561430503712755e-08)
</code></p>

**Comment by crocha700** [comment]
Good point. So I've changed two other things besides the fft: implemented a AB3 scheme for time-stepping and changed the coefficient of the filter from 18.4 to 24.5. The former is used for single precision. The basic idea is to choose this coefficient is to require that the fourier coefs are zero to within machine precision for k > k_cutoff (see Joe LaCasce's thesis).

Reverting these two changes the q1norm test fails "less badly" on my MacPro (anaconda 64-bit)
<code>
 q1norm: 9.560060475638711e-08 Traceback (most recent call last): File "test_twolayer_qg.py", line 89, in test_the_model() File "test_twolayer_qg.py", line 42, in test_the_model np.testing.assert_allclose(q1norm, 9.561430503712755e-08, rtol) File "/Users/crocha/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose verbose=verbose, header=header) File "/Users/crocha/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare raise AssertionError(msg) AssertionError: Not equal to tolerance rtol=1e-15, 
atol=0 (mismatch 100.0%) 
x: array(9.560060475638711e-08) 
y: array(9.561430503712755e-08)
</code>

**Comment by crocha700** [comment]
Good point. So I've changed two other things besides the fft: implemented a AB3 scheme for time-stepping and changed the coefficient of the filter from 18.4 to 24.5. The former is used for single precision. The basic idea is to choose this coefficient is to require that the fourier coefs are zero to within machine precision for k > k_cutoff (see chapter 2 of [Joe LaCasce's thesis](www.dtic.mil/cgi-bin/GetTRDoc?AD=ADA325953
)).

Reverting these two changes the q1norm test fails "less badly" on my MacPro (anaconda 64-bit)

<code>
 q1norm: 9.560060475638711e-08 Traceback (most recent call last): File "test_twolayer_qg.py", line 89, in test_the_model() File "test_twolayer_qg.py", line 42, in test_the_model np.testing.assert_allclose(q1norm, 9.561430503712755e-08, rtol) File "/Users/crocha/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose verbose=verbose, header=header) File "/Users/crocha/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare raise AssertionError(msg) AssertionError: Not equal to tolerance rtol=1e-15, atol=0 (mismatch 100.0%) 
x: array(9.560060475638711e-08) 
y: array(9.561430503712755e-08)
</code>

**Comment by rabernat** [comment]
Yes, both those changes that you describe should make the code more accurate, not less.

After reverting your changes, the mismatch in q1norm (9.560 vs 9.561) is of the same order (and even a bit smaller) than the pre-change platform-dependent mismatch (9.565 vs. 9.561).

Based on that, I am inclined to just go with the "new" test values that I put in recently, which reflect the more accurate solution. Malte, how would you feel about that?

Then we can tackle separately the issue of the platform-dependent (small) mismatches.

**Comment by MFJansen** [comment]
Cesar, I'm not sure I exactly understand your point about the coefficient in the exponential of the filter. What exactly is k_cutoff here. If I remember correctly the "cutoff wavenumber" specified via c_phi in the script is the wavenumber below which the filter doesn't do any filtering anymore (which is different to the wavenumber above which the filter does 100% filtering to within machine precision - which I think is the k_cutoff you are referring to). Given c_phi, the scale where the Fourier coefficients will be zero to within machine precision (your k_cutoff) certainly depends on the exponential factor, but I'm not sure how to decide what's right here. (I actually had used different shaped filters before - and I think the code that I originally got from Glenn used something different as well. The reason I reverted it to the current (or now previous) formulation, is that there was a citable reference for that (Arbic and Flierl 2003, I believe - but unfortunately the journal's website is down right now so I can't check my reference).) Somehow your link to Joe's thesis doesn't work for me.

With regards to the 3rd order time-stepping: does this add any significant computational cost (either directly, or indirectly by changing the required cfl number)? If not, I agree that we can just adopt it and correct the test script accordingly. If it does, I would propose to maybe have the third order scheme as an alternative option.

**Comment by crocha700** [comment]
Arbic and Flierl never discuss from where that number comes from. In fact, the only place I've seen a discussion is in Joe LaCasce's thesis, chapter 2 (I'm positive this was Glenn's idea). Yes the cutoff wavenumber is specified via c_phi (really just a normalized k_cutoff).

I'm OK to reverting back to the previous value – the choice of the filter is arbitrary anyway. I've been discussion a lot with Bill about "filter vs. hyper viscosity". No good answer, though he prefers the latter and I the former.

Because AB schemes are explicit "multi-step" ,  AB3 just adds storage  to AB2 (a couple of additions). Ideally we should have other options of time stepping too -- I personally like  RK4, though it is much more costly AB2/AB4...

**Comment by MFJansen** [comment]
The question of what's the "best" filter of course is a complicated one, and there's obviously a lot of literature out there on this. I believe it's really a physical question and not just one of numerics -- the filter represents the transfer of enstrophy to unresolved scales. The ideal shape will depend significantly on the resolution and other flow properties (mostly the scale of the largest eddies) (e.g. Kitios, Frederiksen, Zidikheri 2013, Ocean Modeling). I personally would even argue that the ideal sub-grid closure is not even strictly negative definite (Jansen and Held 2014, Ocean modeling) - but I don't think we want to get into that (at least not for now and for our "default" case).  I would somewhat prefer to stick with the old values for the filter, simply since these have been used successfully in many experiments before. I'm not convinced that the use of double vs. single precision justifies a significant steepening of the filter - in fact I would guess that wavenumbers where the filter goes to zero to within single precision should be effectively eliminated (i.e. not significantly contributing to the dynamics) even if they are formally not quite zero when using double precision.

We can probably afford a bit of extra storage, so I'm fine with just keeping AB3. If you want to implement a more costly higher order scheme, I would request that it is implemented as an alternative option, since I think that there are many applications where a highly accurate time stepping is not as important as speed.

**Comment by crocha700** [comment]
I agree. And we could have that value as default. The filter parameters could then be an option that the user can play with.

I agree that time-stepping schemes should be optional. This resonates with the idea of working in separating the kernel from wrappers. Now the fact that other time-stepping schemes require more computations does not necessarily mean that they will effectively slow down the code. RK schemes have better stability properties than AB. So, if one is not interested in accuracy, one could simply take larger time step in a RK scheme and still accomplish the same task in the same amount of time of a AB scheme. (The only advantage I see in AB schemes is that they're really easy to implement).

These are all interesting things we could think about, but I think it is not time to have those discussions. The real problem we're facing is the lack of consistency among different systems. The mismatch is relatively small, but still very significant compared to the double precision. So the real question is whether this is  a problem of pyqg. That is, is there something we could do in the level of this code to avoid those fluctuations? I think this is the urgent task, because this might, sooner or latter, come back and bite us.

**Comment by rabernat** [comment]
I just pushed a commit making the filter factor a parameter.
ff9f93fb91c1a7a35ae56d90b4dfee2e8a4b9566

In trying to do the same for AB3, I found a bug in Cesar's Adams Bashforth modifications, which I am writing up now.

**Comment by MFJansen** [comment]
Cesar, I must admit that I don't understand implicit schemes very well, but I agree that it would be nice to have options.

I also agree that it should be a priority now to figure out why we don't get exact reproducibility across platforms. One (maybe the main) problem with not having bitwise reproducibility is that it makes tests very hard. (How to easily and unambiguously test whether answers have changed in any "significant" way, if they aren't exactly identical?)

**Comment by crocha700** [comment]
RK schemes are fully explicit – they're self-starting, "multi-stage" schemes (multi-sub-step as opposed to multi-step AB).

**Comment by MFJansen** [comment]
Then I'm confused about how one could get away with a much larger time step (aren't you limited by cfl?). This should probably be a separate discussion though - we shouldn't hijack this thread. As for how to deal with this, I think we agreed that we adopt AB3 as the default for now, and we can add different options later. You can email me or open another thread if you want to keep talking about time-stepping schemes (and I'm certainly interested to learn more).

**Comment by rabernat** [comment]
One goal of this project is to have an easy way to experiment with different numerical schemes. We should be able to answer all of the questions raised above:
* Is RK4 / AB3 more accurate than AB2?  
* Is it more expensive?

etc... If we set things up properly this will be a breeze to do.

**Comment by rabernat** [comment]
Guys, I just pushed a [commit](f3e6d81bb1d30497529241cc14d7488d4a2b91e5) which tries to recover the original test results in the new code, by using AB2 and the old filter parameter. The problem is that, due to this [other issue](https://github.com/rabernat/pyqg/issues/5), I can't run the new code on my one machine that actually reproduced the original solution and passed the original test.

So could someone (Malte?) update to the latest master and then try test_twolayer_qy again? Please report your results.

**Comment by crocha700** [comment]
I updated my fork with the  newest version. Still fails for me.

<pre><code>
schwartz:tests$ python test_twolayer_qg.py
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 24 days
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 24 days
t=               0, tc=         0: cfl=0.021228, ke=0.000019292, T_e=527.025961099
t=        12800000, tc=      1000: cfl=0.021195, ke=0.000019292, T_e=527.025961099
t=        25600000, tc=      2000: cfl=0.021312, ke=0.000035739, T_e=387.196672142
t=        38400000, tc=      3000: cfl=0.026760, ke=0.000089148, T_e=245.158987437
t=        51200000, tc=      4000: cfl=0.042379, ke=0.000222603, T_e=155.142113219
t=        64000000, tc=      5000: cfl=0.066535, ke=0.000556096, T_e=98.153530025
t=        76800000, tc=      6000: cfl=0.105075, ke=0.001390424, T_e=62.077902117
t=        89600000, tc=      7000: cfl=0.108474, ke=0.003477621, T_e=39.253154602
time:       9.3312e+07
Traceback (most recent call last):
  File "test_twolayer_qg.py", line 106, in <module>
    test_the_model()
  File "test_twolayer_qg.py", line 48, in test_the_model
    np.testing.assert_allclose(q1norm, 9.561430503712755e-08, rtol)
  File "/Users/crocha/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/Users/crocha/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-15, atol=0

(mismatch 100.0%)
 x: array(9.558871760428219e-08)
 y: array(9.561430503712755e-08)

</code></pre>

**Comment by rabernat** [comment]
Cesar, that is exactly the same qnorm that I get:
9.558871760428219e-08

**Comment by MFJansen** [comment]
I just checked out the master branch and tested on my old laptop (where the test used to pass), but it's crashing.
ValueError: operands could not be broadcast together with shapes (32,17) (32,32)

**Comment by francispoulin** [comment]
I just updated my pyqg to the latest branch and found that both my mac laptop and linux desktop seemed to have the same problem with the tolerance.

Mac:
test_twolayer
t=               0, tc=         0: cfl=0.021228, ke=0.000019292, T_e=527.025961099
t=        12800000, tc=      1000: cfl=0.021195, ke=0.000019292, T_e=527.025961099
t=        25600000, tc=      2000: cfl=0.021312, ke=0.000035739, T_e=387.196672142
t=        38400000, tc=      3000: cfl=0.026760, ke=0.000089148, T_e=245.158987437
t=        51200000, tc=      4000: cfl=0.042379, ke=0.000222603, T_e=155.142113219
t=        64000000, tc=      5000: cfl=0.066535, ke=0.000556096, T_e=98.153530025
t=        76800000, tc=      6000: cfl=0.105075, ke=0.001390424, T_e=62.077902117
t=        89600000, tc=      7000: cfl=0.108474, ke=0.003477621, T_e=39.253154602
time:       9.3312e+07
Traceback (most recent call last):
  File "test_twolayer_qg.py", line 107, in <module>
    test_the_model()
  File "test_twolayer_qg.py", line 49, in test_the_model
    np.testing.assert_allclose(q1norm, 9.561430503712755e-08, rtol)
  File "/Applications/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/Applications/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-15, atol=0

(mismatch 100.0%)
 x: array(9.558871760428219e-08)
 y: array(9.561430503712755e-08)

test_advection:
Traceback (most recent call last):
  File "test_advection.py", line 43, in <module>
    test_advect()
  File "test_advection.py", line 34, in test_advect
    jacob = qg_model.ifft2(m,jacobh)
AttributeError: 'module' object has no attribute 'ifft2'



Linux box:
test_twolayer:
t=               0, tc=         0: cfl=0.021228, ke=0.000019292, T_e=527.025961099
t=        12800000, tc=      1000: cfl=0.021195, ke=0.000019292, T_e=527.025961099
t=        25600000, tc=      2000: cfl=0.021312, ke=0.000035739, T_e=387.196672142
t=        38400000, tc=      3000: cfl=0.026760, ke=0.000089148, T_e=245.158987437
t=        51200000, tc=      4000: cfl=0.042379, ke=0.000222603, T_e=155.142113219
t=        64000000, tc=      5000: cfl=0.066535, ke=0.000556096, T_e=98.153530025
t=        76800000, tc=      6000: cfl=0.105075, ke=0.001390424, T_e=62.077902117
t=        89600000, tc=      7000: cfl=0.108637, ke=0.003477621, T_e=39.253154589
time:       9.3312e+07
Traceback (most recent call last):
  File "test_twolayer_qg.py", line 107, in <module>
    test_the_model()
  File "test_twolayer_qg.py", line 49, in test_the_model
    np.testing.assert_allclose(q1norm, 9.561430503712755e-08, rtol)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-15, atol=0

(mismatch 100.0%)
 x: array(9.555974272489496e-08)
 y: array(9.561430503712755e-08)

test_advection:
Traceback (most recent call last):
  File "test_advection.py", line 43, in <module>
    test_advect()
  File "test_advection.py", line 34, in test_advect
    jacob = qg_model.ifft2(m,jacobh)
AttributeError: 'module' object has no attribute 'ifft2'


If anyone would like me to try something else please let me know.

**Comment by crocha700** [comment]
It's interesting that you get two different answers for test_twolayer. Do you have different versions of numpy? is mklfft installed?

(The last commits broke test_advection; I'll fix that soon).

**Comment by crocha700** [comment]
Guys, I liked Francis idea about trying a simpler calculation in order to find out the source of differences across platforms. So I programmed a [simple code to solve the 1D Burgers equation](http://nbviewer.ipython.org/github/crocha700/comp_gfd/blob/master/notebooks/burgers.ipynb) (with a bit a viscosity to avoid shocks). This is the simplest pseudo-spectral calculation I could think of. After integrating the equation for a while, I evaluated a norm, the sum of $u^2$ at every point (normu_mac_cesar). It would be useful to test if you obtain the same norm to machine double precision. This calculation was done on my MacPro with Anaconda 64-bit.

(I worked on a Fortran 90 version of the code that uses fftw3; I need to double check to see if I have no inconsistencies. I'm getting a difference of 1.e-2 between Fortran and Python, which  seems big for me to believe.)

**Comment by francispoulin** [comment]
Hello,

On my Mac I am using numpy 1.9.2 that is the mkl version.  I didn't install mklfft but I presume it's using that by default?  If you tell me how to check I will certainly do that.

On my PC I'm using numpy 1.8.2 (ubuntu's latest) without mkl. 

I just downloaded the Burger notebook and I will try and run it today. If it is possible to show consistency than this is an easier case, but as Malte says, it is chaotic.  If we have tests it should probably only be for a short time.

In my two test cases, all the digits printed looked identical up until the last print out.  Maybe we should focus a test case on a coarse grid for a short time.  It's easier and at least we can prove that the basic system works, even though chaos will poke its head in quickly enough.

**Comment by francispoulin** [comment]
I just ran the notebook on my mac and (not surprisingly) all the numbers were the same.
I tried it on my PC but I can't load it because I am still using the old notebook.  I get "Unsupported JSON nbformat version 4".  I need to fix that.

**Comment by crocha700** [comment]
Malte, I thought you said you and Ryan were getting bitwise reproducibility in the "test_twolayer" between Matlab and Python.

**Comment by MFJansen** [comment]
I should have also added that this result for q1norm (9.558871760428219e-08) is also what I get on my desktop - which is NOT using MKL. Can we confirm that we get this result consistently when using the default numpy library.

Francis: you should be able to check like this:
In [3]: numpy.fft.fft2
Out[3]: <function numpy.fft.fftpack.fft2>

This output shows that I'm not using MKL (otherwise it would say something like "<function fastnumpy.mklfft.fft2>") 

I still think that it will be very hard to properly test the code if we don't have bitwise reproducibility. If we do only very few timesteps and/or allow a somewhat larger error, than we may quite easily miss errors e.g. in the non-linear term. As a note: GFDL's "IPCC-class" Ocean model has bitwise reproducibility across multiple machines. It seems a bit sad if we can't get that with a simple QG model. However, if Python's build in functions aren't coded in a way that gives us bitwise reproducibility we'll probably have to give up on that.

Bruce: I do recall that we did get bitwise identical results between Matlab and Python last summer. But I haven't tried to reproduce that since.

**Comment by crocha700** [comment]
Let's try Malte's suggestion. I do get machine precision in the difference between A and the inverse of fft(A). 
 
<pre><code>

import numpy as np
from numpy import pi

N = 64
L = 2.*pi
dx = L/N
x = np.arange(0,L,dx)
y = x.copy()

x,y = np.meshgrid(x,y)

A = 1./( 1. + (x-pi)**2+ (y-pi)**2 )

Ah = np.fft.rfft2(A)

Af = np.fft.irfft2(Ah)

print (np.abs(A-Af)).max()
3.33066907388e-16
</code></pre>

This was on my mac with anaconda 64-bit and
<pre><code>
In [2]: np.version.version
Out[2]: '1.9.2'

In [3]: np.fft.rfft
Out[3]: <function mklfft.fftpack.rfft>
</code></pre>

**Comment by MFJansen** [comment]
Francis: I can't see the output in your post - I think you have to remove the angle brackets so that they are not interpreted as formatting by the thread editor.

**Comment by MFJansen** [comment]
For the fft, I'm getting the same results as Bruce on my iMac without MKL:

import numpy as np
from numpy import pi

N = 64
L = 2.*pi
dx = L/N
x = np.arange(0,L,dx)
y = x.copy()

x,y = np.meshgrid(x,y)

A = 1./( 1. + (x-pi)**2+ (y-pi)**2 )

Ah = np.fft.rfft2(A)

Af = np.fft.irfft2(Ah)

print (np.abs(A-Af)).max()
3.33066907388e-16

np.version.version
Out[9]: '1.8.1'

np.fft.rfft
Out[10]: 'function numpy.fft.fftpack.rfft'

**Comment by MFJansen** [comment]
This won't work at all on my MacBook with MKL though, since rfft is messed up, as discussed previously

**Comment by francispoulin** [comment]
On each of my computers I have two versions of python: Anaconda and not Anaconda. I typed the np.fft.rfft on each of them and I got the same kind of output, but the details were different.  I checked the path and this was the case even if it was not using the MKL library.  Certainly the path was not pointing there at all.  

All that to say that I'm not sure if this is a sure fire way to see if one is using MKL.  Having said that I don't know what is.

**Comment by francispoulin** [comment]
I just discovered that my anaconda versions did not have accelerate, which has mklfft.  I just installed it on my macbook and still got the same result from the fft test.

**Comment by MFJansen** [comment]
Francis: can you specify what the output was? (from just typing in np.fft.rfft)

**Comment by francispoulin** [comment]
With Anaconda it is,

>>> np.fft.rfft
<function rfft at 0x10536e5f0>

Without Anaconda it is

>>> np.fft.rfft
<function rfft at 0x10383e0c8>

**Comment by crocha700** [comment]
@francispoulin : suppress the angle brackets before publishing the result. (The angle brackets have a special meaning in markdown, so it is not showing your results...)

**Comment by francispoulin** [comment]
Sorry about that.

Anaconda:
np.fft.rfft
<function rfft at 0x10536e5f0>

Non-Anaconda
np.fft.rfft
<function rfft at 0x10383e0c8>

**Comment by crocha700** [comment]
So FFT2 works to machine precision. That doesn't surprise me that much since these codes are generally widely tested, though people were sloppy with mklfft.rfft2.

One thing that's probably breaking the machine precision accuracy is that when we compute derivatives, we multiply by k...Say you multiply something that is the edge of being zero within machine precision by k=10. This may lead to a nonzero (but small) result...This things can build up, maybe?

**Comment by MFJansen** [comment]
Sorry, I still can't see the output in Francis' posts. Is that just me?

**Comment by francispoulin** [comment]
Sorry for not getting this right sooner. If I have angular brackets it seems to suppress the output.   I updated my comment above

I agree that fft and ifft should be standard.  One concern is that the order that I learned was
[0:N/2, -N/2+1,-1]  but from looking at numpy I think they have [0:N/2-1, -N/2:-1].  Does it matter what we call the middle wavenumber: N/2 or -N/2.  The cosine won't care but the sine will be off by a sign.

**Comment by MFJansen** [comment]
Francis: Sorry, I get some actual readable information when I do that; not sure what's different... 

Cesar: what exactly do you mean when saying that "FFT2 works to machine precision"? If we get non-identical output (in any digit) on different machines, that suggests to me that the numbers differ by at least one bit, which should be enough to cause much larger differences after a finite time integration of a chaotic system. 

Honestly, I'm generally getting quite confused about who is referring to what exact test and criterion (and on what machine and using which package). Maybe we should really try to have a phone call?

**Comment by MFJansen** [comment]
I just pushed a new version of the test_twolayer_qg called test_twolayer_qg_fftw onto the develop branch.
This one has the results from my iMac (using fftw) as the "correct" answer. Please everybody go check if this passes on machines with fftw.

**Comment by bastorer** [comment]
This test fails on my MacMini. Output included below.

t=               0, tc=         0: cfl=0.021228, ke=0.000019292, T_e=527.025961099
t=        12800000, tc=      1000: cfl=0.021195, ke=0.000019292, T_e=527.025961099
t=        25600000, tc=      2000: cfl=0.021312, ke=0.000035739, T_e=387.196672142
t=        38400000, tc=      3000: cfl=0.026760, ke=0.000089148, T_e=245.158987437
t=        51200000, tc=      4000: cfl=0.042379, ke=0.000222603, T_e=155.142113219
t=        64000000, tc=      5000: cfl=0.066535, ke=0.000556096, T_e=98.153530025
t=        76800000, tc=      6000: cfl=0.105075, ke=0.001390424, T_e=62.077902117
t=        89600000, tc=      7000: cfl=0.108190, ke=0.003477621, T_e=39.253154575
time:       9.3312e+07
Traceback (most recent call last):
  File "test_twolayer_qg_fftw.py", line 115, in <module>
    test_the_model()
  File "test_twolayer_qg_fftw.py", line 56, in test_the_model
    np.testing.assert_allclose(q1norm, 9.557023878260622e-08, rtol)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-15, atol=0

(mismatch 100.0%)
 x: array(9.560228567668638e-08)
 y: array(9.557023878260622e-08)

**Comment by crocha700** [comment]
Fails on my MacPro with Anaconda-64, numpy 1.9.1, pyfftw 0.9.2.

<pre><code>
Not equal to tolerance rtol=1e-15, atol=0

(mismatch 100.0%)
 x: array(9.55987938961006e-08)
 y: array(9.557023878260622e-08)
</code></pre>

The difference is 
<pre><code>
2.8555113494374955e-11
</code></pre>
This error is one order go magnitude larger than the error we get by simply computing the DFT of a field back-and-forth a number of times equivalent to the number of time steps in this test (see test_fftw.py; I obtain an error of the same order when I do the same test calling ftw in fortran 90.)

**Comment by MFJansen** [comment]
Ok. I guess FFTW is actually just straight out "nondeterministic" if used in the default way (see http://www.fftw.org/faq/section3.html#nondeterministic). I confirmed this: the test fails after only restarting the kernel. It looks like one may be able to "fix" this (for test purposes) - but as of now I don't understand how.

**Comment by MFJansen** [comment]
I just modified some code so that the test now uses a certain planner for the fftw that is supposed to make the results reproducible (use of this planner is now controlled by the "teststyle" option). It seems to work in the sense that at least results don't seem to change anymore between kernel restarts. Of course I don't know if that makes it machine independent (I doubt it but it's worth a try). If you don't mind running the latest version of the "test_twolayer_qg_fftw" on your machines, I would be interested to hear what you get.

**Comment by crocha700** [comment]
did you push the commit?

**Comment by MFJansen** [comment]
oops apparently my push failed ... working on it..

**Comment by MFJansen** [comment]
should be on "develop" now

**Comment by crocha700** [comment]
Passes here on my MacPro!

**Comment by francispoulin** [comment]
I have tried this on my mac, my PC and Ben has tried it on a Mac and we seem to always get this error.

Is there something else we need to download on the deveopment branch?

/Applications/anaconda/bin/python test_twolayer_qg_fftw.py 
Traceback (most recent call last):
  File "test_twolayer_qg_fftw.py", line 116, in <module>
    test_the_model()
  File "test_twolayer_qg_fftw.py", line 30, in test_the_model
    diagnostics_list='all'      # which diagnostics to output)
TypeError: __init__() got an unexpected keyword argument 'teststyle'

**Comment by MFJansen** [comment]
There are changes to the model itself, so you need to pull the whole branch (or at least the new model.py). Then you might need to restart your kernel to make sure the new model is imported.

**Comment by francispoulin** [comment]
I admit that I am new to git so maybe I'm making a silly mistake.  But we are using the update version of the development branch on all of our computers.  We are running python each time so I don't think we need to restart the kernel (no ipython notebook here).

Any ideas what I might be doing wrong?

**Comment by francispoulin** [comment]
Also, I remember learning that when FFTW is installed there is the option to install double or single or even possibly other levels of accuracy.  I would hope that any basic FFTW would use double but that might not be the case.  We might want to be careful that someone trying this out might have installed FFTW with single precision and then there is no way to expect the same accuracy.

**Comment by crocha700** [comment]
As Malte mentioned, there is a small change to model.py. You should pull or fetch (better) the latest version and then merge it into yours:

Set pyqg as upstream 
$ git remote add upstream https://github.com/rabernat/pyqg

Grab the changes 
$ git fetch upstream

Merge into you develop branch
$ git merge upstream/develop

(I'll include a simple git workflow in the documentation. )

**Comment by MFJansen** [comment]
Cesar: Since the test succeeded on one of your computers, but failed on the other one, could you confirm that just a simple fft (using fftw with the "planner_effort='FFTW_ESTIMATE' ") yields non-identical results on those two computers? I would like to make sure that it is indeed the fft that causes the difference - but I only have one computer with fftw...

**Comment by francispoulin** [comment]
Cesar:  Thanks for the advice.  I tried the list of commands on both of my computers and they both have the same problem with teststyle.  Might there be something else that I need to do?

**Comment by francispoulin** [comment]
Correction: I hadn't installed pyqg correctly.

Now it works on my Mac but fails on  my PC, but does have single.  

t=        12800000, tc=      1000: cfl=0.041674, ke=0.000035706
t=        25600000, tc=      2000: cfl=0.041792, ke=0.000089067
t=        38400000, tc=      3000: cfl=0.042141, ke=0.000222400
t=        51200000, tc=      4000: cfl=0.042376, ke=0.000555587
t=        64000000, tc=      5000: cfl=0.066479, ke=0.001389150
t=        76800000, tc=      6000: cfl=0.105043, ke=0.003474434
t=        89600000, tc=      7000: cfl=0.122633, ke=0.002861952
time:       9.3312e+07
Traceback (most recent call last):
  File "test_twolayer_qg_fftw.py", line 116, in <module>
    test_the_model()
  File "test_twolayer_qg_fftw.py", line 57, in test_the_model
    np.testing.assert_allclose(q1norm, 9.55790786669029e-08, rtol)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-15, atol=0

(mismatch 100.0%)
 x: array(9.556950699530468e-08)
 y: array(9.55790786669029e-08)

**Comment by crocha700** [comment]
I ran
<pre><code>
import numpy as np
from numpy import pi
import pyfftw as fftw

N = 32

x = np.arange(0,2.*pi,2.*pi/N)
y = x.copy()
x,y = np.meshgrid(x,y)

A = 1./( 1. + (x-pi)**2 + (y-pi)**2 )

Ah = fftw.interfaces.numpy_fft.rfft2(A,planner_effort='FFTW_ESTIMATE')
Aw = fftw.interfaces.numpy_fft.irfft2(Ah,planner_effort='FFTW_ESTIMATE')
</code></pre>
I get the exact same results on both machines. I saved  the results computed on my Mac, and loaded them into the linux machine, ran the code and compared every element of the A, Ah, and Aw.  They're bitwise equal.

**Comment by crocha700** [comment]
On the linux machine I get the same error as Franci's (within 1.e-15):

9.556950699530467e-08

**Comment by MFJansen** [comment]
Interesting, so maybe some other part of our code is evaluated slightly differently on Mac vs Linux?

**Comment by francispoulin** [comment]
I verified Cesar's result and my mac and pc yield exactly the same result to 1e-16.

Good question as to what Mac's and PC's do differently.  Hmm...

**Comment by francispoulin** [comment]
I went into model.py and decided to output the KE with more decimal places to compare my PC and Mac results.  Results are below.

It seems that after the first time step the KE is different in the 16 significant digit.  In the the next time step it is in the 14th and it gradually builds.  I don't pretend to know what the problem is but I wanted to point out that there are, albeit small, differences at the first step.   I have only looked at KE.  I think ti would be sensible to look at the norm of the streamfunction and PV to see where the differences arise.   

Mac:
t=        12800000, tc=      1000: cfl=0.041674, ke=0.0000357061110613667818
t=        25600000, tc=      2000: cfl=0.041792, ke=0.0000890665356179239055
t=        38400000, tc=      3000: cfl=0.042141, ke=0.0002223998374384436193
t=        51200000, tc=      4000: cfl=0.042376, ke=0.0005555872612684647268
t=        64000000, tc=      5000: cfl=0.066479, ke=0.0013891504037420120653
t=        76800000, tc=      6000: cfl=0.105043, ke=0.0034744339810996371573
t=        89600000, tc=      7000: cfl=0.122818, ke=0.0028622340349587441916

PC:
t=        12800000, tc=      1000: cfl=0.041674, ke=0.0000357061110613667615
t=        25600000, tc=      2000: cfl=0.041792, ke=0.0000890665356179237970
t=        38400000, tc=      3000: cfl=0.042141, ke=0.0002223998374384439716
t=        51200000, tc=      4000: cfl=0.042376, ke=0.0005555872612684647268
t=        64000000, tc=      5000: cfl=0.066479, ke=0.0013891504037420133663
t=        76800000, tc=      6000: cfl=0.105043, ke=0.0034744339811256493358
t=        89600000, tc=      7000: cfl=0.122633, ke=0.0028619516632027021223
